set(sources ${sources}
	src/MES.cpp
	src/MES.h
	src/logger.h
	src/logger.cpp
	src/event.h
	src/event.cpp
	src/scene.h
	src/scene.cpp
	src/utility.h
	src/err.cpp
	src/err.h
	src/obj.cpp
	src/obj.h
	src/serialization.h
	src/serialization.cpp
	src/UI.cpp
	src/UI.h
	src/UIManager.cpp
	src/UIManager.h
)